project_name: envoke
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: envoke
    main: ./cmd/envoke
    binary: envoke
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/eficode/secure-handling-of-secrets/internal/version.Version={{.Version}}
      - -X github.com/eficode/secure-handling-of-secrets/internal/version.Commit={{.ShortCommit}}
      - -X github.com/eficode/secure-handling-of-secrets/internal/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: true
